version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-example/
hooks:
  BeforeInstall:
    - location: 01-hello-world/scripts/install_dependencies.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: 01-hello-world/scripts/stop_app.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: 01-hello-world/scripts/start_app.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: 01-hello-world/scripts/monitor_app.sh
      timeout: 60
      runas: ec2-user